stages:
  - build
  - publish
  - deliver

variables:
  BUILD_SVR_PATH: "C:\\Users\\commonuser\\Documents\\mss-academy-projects\\specialization\\build_svr"
  BIN_REPO_SVR_PATH: "C:\\Users\\commonuser\\Documents\\mss-academy-projects\\specialization\\bin_repo_svr"


copy_to_local_folder:
  stage: build
  
  script:
    - Write-Host "Executing copy"
    - $match = $env:CI_COMMIT_REF_NAME -match "^r_jsb_\d+_\d+$"
    - |
      if (Test-Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME") {
        Remove-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME" -Recurse -Force;
        New-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME" -ItemType Directory -Force;
      }
    - |
      if ($match) {
        if (Test-Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME") {
          Remove-Item -Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME" -Recurse -Force;
        }
        New-Item -Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME" -ItemType Directory -Force;
        Copy-Item -Path "$env:CI_PROJECT_DIR\*" -Destination "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME" -Recurse;
      } else {
        Write-Host "Branch name does not match the pattern. Skipping...";
        exit 1;
      }
  only:
    - /^r_jsb_\d+_\d+$/

build_jar_file:
  stage: build
  before_script:
    - $ARTIFACT_PATH="${BUILD_SVR_PATH}\${env:CI_COMMIT_REF_NAME}\target\*.jar"
  script:
    - cd "$BUILD_SVR_PATH\\$env:CI_COMMIT_REF_NAME"
    - "& $BUILD_SVR_PATH\\$env:CI_COMMIT_REF_NAME\\build\\build.ps1"
    - |
      if(Test-Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar") {
        Remove-Item -Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar" -Force
      }
    - tar -cf "$env:CI_COMMIT_REF_NAME.tar" "bin" "deploy" "config" "test"
  artifacts:
    paths:
      - $ARTIFACT_PATH
 
copy_to_bin_repo:
  stage: publish
  script:
    - |
      if(Test-Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar") {
        Remove-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar";
      }
    - New-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME" -ItemType Directory -Force;
    - Copy-Item -Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar" -Destination "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar";
    - tar -tf "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar";

setup_ssh:
  stage: deliver
  script:
    - $env:SSH_AUTH_SOCK = Start-Service ssh-agent
    - Set-Content -Path commonuser\.ssh\gitlab-ci -Value $env:SSH_PRIVATE_KEY
    - chmod 600 commonuser\.ssh\id_rsa
    - scp /path/on/runner/file.tar $env:REMOTE_USER@$env:REMOTE_HOST:/destination/path/on/remote/
    - ssh $env:REMOTE_USER@$env:REMOTE_HOST "your-command-here"
# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDZ0eFjWTc/c6DpVXN8XAzhykX+60f+B5lGigh5UuyJcyJM6+Gbj9uqJru8eOzY4zX65W+DVq5Pov3dbaGJp29ktmKGBbuBRl2gP5ed39LEJ20UdVlVpaKdk9S1K0CUveQYlBa0/Xi8kUM7h+iFiWXo+moRzNJaRcwtCp80wGL6jRVbnKyco4UXl1F0TSs2lMgnb5AoaDLuYr40ABN4g3eoJ9BkzYjKz/LIxN7Ire8EaZjW+cwyKTn0/KUXprQ/GpPyKsGSfO1vLFM5P5Xg/lcWj3qF9FtP3961cvauSN2dNOYybHxIH3J9IxVmLQMoFwliNgKptR54+OfDdyln117sHIHrCzr1gL4aPz5q77XO3fkMXY1RBx2HE1SypqDN45pL2kw+4kAFgDjmSXb5InbMawuLJSnIB4+IYbNWouxmU60c7tDps7Nljqia3bdE7jB1pwDst3bIP9hkPrag8gK1YRLV6ZeAVuwm5+GiLJZQJRs6kTmYXak9BB3Y9sNoNNLIV3a2SWY7daB+1j1tfLOPZTPHYXIcsL6ZFq2JsMNbLsgMqKTtDXWFONkvNi4gmo9F5LBxUqNW5KJNhNCOqWYrT2vcA7ItURifXSIjdQYF2VNZWXQE1EiNcO9gvXA2xLmfNwlbEoqk6UyvEGA2vjrEIwqHzuoAXesn4ZcfL9rcjQ== gitlab-cicd
