stages:
  - transfer_build
  - build
  - transfer_bin
  - ssh

variables:
  BUILD_SVR_PATH: "C:\\Users\\commonuser\\Documents\\mss-academy-projects\\specialization\\build_svr"
  BIN_REPO_SVR_PATH: "C:\\Users\\commonuser\\Documents\\mss-academy-projects\\specialization\\bin_repo_svr"


copy_to_local_folder:
  stage: transfer_build
  
  script:
    - Write-Host "Executing copy"
    - $match = $env:CI_COMMIT_REF_NAME -match "^r_jsb_\d+_\d+$"
    - if (Test-Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME") {
        Remove-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME" -Recurse -Force;
        New-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME" -ItemType Directory -Force;
      }
    - if ($match) {
        if (Test-Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME") {
          Remove-Item -Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME" -Recurse -Force;
        }
        New-Item -Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME" -ItemType Directory -Force;
        Copy-Item -Path "$env:CI_PROJECT_DIR\*" -Destination "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME" -Recurse;
      } else {
        Write-Host "Branch name does not match the pattern. Skipping...";
        exit 1;
      }
  only:
    - branches

build_jar_file:
  stage: build
  before_script:
    - $ARTIFACT_PATH="${BUILD_SVR_PATH}\${env:CI_COMMIT_REF_NAME}\target\*.jar"
  script:
    - Write-Host $ARTIFACT_PATH
    - Write-Host "$BUILD_SVR_PATH\\$env:CI_COMMIT_REF_NAME\\build\\build.ps1"
    - cd "$BUILD_SVR_PATH\\$env:CI_COMMIT_REF_NAME"
    - "& $BUILD_SVR_PATH\\$env:CI_COMMIT_REF_NAME\\build\\build.ps1"
    - tar -cf "$env:CI_COMMIT_REF_NAME.tar" "build" "bin" "deploy" "config"
  artifacts:
    paths:
      - $ARTIFACT_PATH

copy_to_bin_repo:
  stage: transfer_bin
  script:
    - if(Test-Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar") {
        Remove-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar";
      }
      Copy-Item -Path "$BUILD_SVR_PATH\\$env:CI_COMMIT_REF_NAME\\$env:CI_COMMIT_REF_NAME.tar" -Destination "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar" -Recurse;

# prepare_ssh:
#   stage: ssh
#   script:
#     - 