stages:
  - build
  - publish
  - deliver
  - deploy
  - test
  - clear

variables:
  BUILD_SVR_PATH: "C:\\Users\\commonuser\\Documents\\mss-academy-projects\\specialization\\build_svr"
  BIN_REPO_SVR_PATH: "C:\\Users\\commonuser\\Documents\\mss-academy-projects\\specialization\\bin_repo_svr"


copy_to_local_folder:
  stage: build
  
  script:
    - Write-Host "Executing copy"
    - $match = $env:CI_COMMIT_REF_NAME -match "^r_jsb_\d+_\d+$"
    - |
      if (Test-Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME") {
        Remove-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME" -Recurse -Force;
        New-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME" -ItemType Directory -Force;
      }
    - |
      if ($match) {
        if (Test-Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME") {
          Remove-Item -Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME" -Recurse -Force;
        }
        New-Item -Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME" -ItemType Directory -Force;
        Copy-Item -Path "$env:CI_PROJECT_DIR\*" -Destination "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME" -Recurse;
      } else {
        Write-Host "Branch name does not match the pattern. Skipping...";
        exit 1;
      }
  only:
    - /^r_jsb_\d+_\d+$/

build_jar_file:
  stage: build
  before_script:
    - $ARTIFACT_PATH="${BUILD_SVR_PATH}\${env:CI_COMMIT_REF_NAME}\target\*.jar"
  script:
    - cd "$BUILD_SVR_PATH\\$env:CI_COMMIT_REF_NAME"
    - "& $BUILD_SVR_PATH\\$env:CI_COMMIT_REF_NAME\\build\\build.ps1"
    - |
      if(Test-Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar") {
        Remove-Item -Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar" -Force
      }
    - tar -cf "$env:CI_COMMIT_REF_NAME.tar" "bin" "deploy" "config" "test"
  artifacts:
    paths:
      - $ARTIFACT_PATH
 
copy_to_bin_repo:
  stage: publish
  script:
    - |
      if(Test-Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar") {
        Remove-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar";
      }
    - New-Item -Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME" -ItemType Directory -Force;
    - Copy-Item -Path "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar" -Destination "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar";
    - tar -tf "$BUILD_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar";

setup_ssh:
  stage: deliver
  script:
    # - $env:SSH_AUTH_SOCK = Start-Service ssh-agent
    # - Set-Content -Path C:\Users\commonuser\.ssh\gitlab-ci -Value $env:SSH_PRIVATE_KEY
    # - icacls "C:\Users\commonuser\.ssh\gitlab-ci" /inheritance:d
    # - icacls "C:\Users\commonuser\.ssh\gitlab-ci" /grant:r "$($env:USERNAME):R"
    - scp "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar" "$($env:REMOTE_USER)@$($env:REMOTE_HOST):\C:\Users\l1ds\group1\"

untar:
  stage: deliver
  script:
    - |
      ssh "$($env:REMOTE_USER)@$($env:REMOTE_HOST)" "New-Item -Path 'C:\Users\l1ds\group1\$($env:CI_COMMIT_REF_NAME)' -ItemType Directory -Force;
      tar -xvf 'C:\Users\l1ds\group1\$($env:CI_COMMIT_REF_NAME).tar' -C 'C:\Users\l1ds\group1\$($env:CI_COMMIT_REF_NAME)';
      powershell -command 'C:\Users\l1ds\group1\$($env:CI_COMMIT_REF_NAME)\deploy\deploy.ps1' -CI_COMMIT_REF_NAME ${CI_COMMIT_REF_NAME};"

integration_testing:
  stage: test
  script:
    - |
      echo "DELETE FROM tmsappdb.accgroup WHERE groupName='project lead';" | ssh l1ds@192.168.0.2 "mysql -u root -ppassword"
    - ssh "$($env:REMOTE_USER)@$($env:REMOTE_HOST)" C:\Users\l1ds\group1\$($env:CI_COMMIT_REF_NAME)\test\test.ps1

clear_docker:
  stage: clear
  script:
    - ssh "$($env:REMOTE_USER)@$($env:REMOTE_HOST)" "docker stop $($env:CI_COMMIT_REF_NAME)"
    - ssh "$($env:REMOTE_USER)@$($env:REMOTE_HOST)" "docker rm $($env:CI_COMMIT_REF_NAME)"
    - ssh "$($env:REMOTE_USER)@$($env:REMOTE_HOST)" "docker rmi $($env:CI_COMMIT_REF_NAME)"
  allow_failure: true

# clear_db:
#   stage: clear
#   script:
#     - |
#       ssh -i "C:\Users\commonuser\.ssh\gitlab-ci" "$($env:REMOTE_USER)@$($env:REMOTE_HOST)" "mysql -u root -ppassword -e 'DROP DATABASE tmsappdb; CREATE DATABASE tmsappdb;'"
#   allow_failure: true

clear_folders:
  stage: clear
  script:
    - |
      if(Test-Path "$BIN_REPO_SVR_PATH\$env:CI_COMMIT_REF_NAME\$env:CI_COMMIT_REF_NAME.tar") {
        ssh "$($env:REMOTE_USER)@$($env:REMOTE_HOST)" "Remove-Item -Path 'C:\Users\l1ds\group1\$($env:CI_COMMIT_REF_NAME)' -Recurse -Force;"
      }
  allow_failure: true


# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPg9gAqbu7Q9cvG4Ui04YSQGGdaJxh9sZbf947YBEJo7fEo6iTWjIIAh8GeTINqfc5pXqns5xaGqgkl/w6XSejXxX+RmesVLeTwNu9Ktg/CLeH08kGcCs0PR3w9F/ciM9465iETPna7yU4QQglxZXfOe3uyQ8DaEr6tcvvqtrn4CgYChrYwBCwVtioCun/so61VQV3zPqrxqF6npKzSXg/kvYsa+MeldV5lcEoen8MpvSXaxxSdP2h3tR0cByt1XLVlAku3Q+Elqq0yk7ygRGx0qLZSbM5Pgd/D2YFdnF10OWyWgf2rF5TgxtR0ii0ADd0c7p67oU3MxXH7MT8KfBY54LMrzGVrAdIpbv9FWmGLeIfbwVH1LARBGLglJfiApx1JWtmk10Cl92hp92sCxXJ5fbqDm4NWULZ4nYtEQ/AUTWtK1ePAE+10NsXhPsAXOHhLeaNhRUZ0WHPFzSp9ZVOLYizZ7IJHhoZxVyWNSaCSckGWhm5AfN+VVnY1BqM9Qh2f/RCy7h9lCeRgh+Hz0ErScjBu0PLA8xnn0OTV+aCo76IceXufXE7sAdyFvNTiONPOgIUflWa04dYsvrJuKftV3cq75dj6KZWfmX0bENZREkt5I4Fo1Af+XSPNcBGrLeet3cZztmL0hP5j7oon9RSK+yzVLtxLGwDvjwGSeeUtw== gitlab-cicd

#eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImlwIjoiMDowOjA6MDowOjA6MDoxIiwidXNlckFnZW50IjoiUG9zdG1hblJ1bnRpbWUvNy4zMi4zIiwiZXhwIjoxNjkzNTA4NDgyfQ.LycVAn0AfuZQoWMHR436BVngPVP3HqCbkq8o1iTB7uLJEFXXzdEFRjgYeBlzELrFjzVytWpK6Ztvva1EkEt2Hw
