stages:
  - transfer

copy_to_local_folder:
  stage: transfer
  script:
    - echo "Executing copy"
    - if echo "%CI_COMMIT_REF_NAME%"| findstr /R "^r_jsb_[0-9]*_[0-9]*$" > nul; then
        md "C:\Users\commonuser\Documents\mss-academy-projects\specialization\build_svr" 2>nul
        xcopy /E /I "%CI_PROJECT_DIR%\*" "C:\Users\commonuser\Documents\mss-academy-projects\specialization\build_svr"
      else
        echo "Branch name does not match the pattern. Skipping..."
      fi
  only:
    - branches