stages:
  - transfer

copy_to_local_folder:
  stage: transfer
  script:
    - mkdir -p "C:\Users\commonuser\Documents\mss-academy-projects\specialization\build_svr" 2>nul
    - xcopy /E /I "%CI_PROJECT_DIR%\*" "C:\Users\commonuser\Documents\mss-academy-projects\specialization\build_svr"
  only:
    - branches
  variables:
    - $CI_COMMIT_REF_NAME =~ /^r_jsb_\d+_\d+$/